#!/bin/bash

set -e

GROMACS_VER=2025.4

# Configure.
cmake \
    -DGMX_TEST_TIMEOUT_FACTOR=4 \
    -DGMX_DISABLE_CUDA_TEXTURES=ON \
    -DCMAKE_INSTALL_PREFIX="$(pwd)/../install" \
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_CUDA_ARCHITECTURES=${SCALE_FAKE_CUDA_ARCH} \
    -DGMX_CUDA_TARGET_SM=${SCALE_FAKE_CUDA_ARCH} \
    -DGMX_CLANG_CUDA=OFF \
    -DGMX_GPU=CUDA \
    -DGMX_BUILD_OWN_FFTW=ON \
    -DGMX_PYTHON_PACKAGE=OFF \
    -DGMX_MPI=OFF \
    -DGMX_PYTHON_BINDINGS=OFF \
    -DGMX_THREAD_MPI=ON \
    -DCMAKE_DISABLE_FIND_PACKAGE_MPI=ON \
    -DGMX_HAVE_GPU_GRAPH_SUPPORT=OFF \
    -DGMX_NNPOT=OFF  \
    -DGMX_OPENMP=OFF \
    -B"build" \
    "gromacs"

make -C build -j"$(nproc)" install
