#!/bin/bash

set -e

# Skip faulty tests. See scale#385.
SKIP="
stdgpu_deque.simultaneous_push_back_and_pop_back
stdgpu_deque.simultaneous_push_front_and_pop_front
stdgpu_deque.simultaneous_push_back_and_pop_front
stdgpu_unordered_map.insert_unique_parallel
stdgpu_unordered_map.emplace_unique_parallel
stdgpu_unordered_map.erase_unique_parallel
stdgpu_unordered_map.insert_and_erase_unique_parallel
stdgpu_unordered_map.insert_range_unique_parallel_custom_execution_policy
stdgpu_unordered_map.bucket_size_sum
stdgpu_unordered_map.count_sum
stdgpu_unordered_map.non_const_device_range
stdgpu_unordered_map.non_const_device_range_same_custom_execution_policy
stdgpu_unordered_map.const_device_range
stdgpu_unordered_map.const_device_range_same_custom_execution_policy
stdgpu_unordered_map.clear
stdgpu_unordered_map.clear_custom_execution_policy
stdgpu_unordered_set.insert_unique_parallel
stdgpu_unordered_set.emplace_unique_parallel
stdgpu_unordered_set.erase_unique_parallel
stdgpu_unordered_set.insert_range_unique_parallel
stdgpu_unordered_set.insert_range_unique_parallel_custom_execution_policy
stdgpu_unordered_set.insert_const_range_unique_parallel
stdgpu_unordered_set.erase_range_unique_parallel
stdgpu_unordered_set.erase_range_unique_parallel_custom_execution_policy
stdgpu_unordered_set.erase_const_range_unique_parallel
stdgpu_unordered_set.bucket_size_sum
stdgpu_unordered_set.count_sum
stdgpu_unordered_set.insert_and_erase_unique_parallel
stdgpu_unordered_set.non_const_device_range
stdgpu_unordered_set.non_const_device_range_same_custom_execution_policy
stdgpu_unordered_set.const_device_range
stdgpu_unordered_set.const_device_range_same_custom_execution_policy
stdgpu_unordered_set.clear
stdgpu_unordered_set.clear_custom_execution_policy
stdgpu_vector.simultaneous_push_back_and_pop_back
"

SKIP=$(echo $SKIP | sed 's/ /:/g')

build/bin/teststdgpu --gtest_filter="-${SKIP}" --gtest_output=xml:stdgpu.xml
