# Plans the per-project builder images so they share as many docker layers as possible.
#
# Builds a graph where each node is a project builder image or a scale-test-$distro
# image. An edge from A to B means A's dockerfile uses B's image as its base. Each
# project image starts out based on scale-test-$distro. It is then split into a chain of
# layer images that each install one package. Packages more projects need go first, so
# projects can share them. Next, each image is
# repointed at the image whose installed packages are the largest subset of its own.
# Then layer images that install nothing or that no image uses are removed. Last, each
# layer image used by only one image is merged into that image.
#
# Reads the `.dependencies` file in each project directory (see README.md for the format).
# Writes a dockerfile for each project and layer image to images/ in the current
# directory, replacing any dockerfiles already there. `ext` packages are installed by
# images/install-ext.sh. Run from the root of test/thirdparty.

import random
import shlex
from abc import ABC, abstractmethod
from collections import Counter
from dataclasses import dataclass
from pathlib import Path

REPO_BASE = Path.cwd()


# Data structures for our graph
class Node(ABC):
    @property
    @abstractmethod
    def name(self) -> str:
        pass

    @property
    @abstractmethod
    def installed(self) -> frozenset[str]:
        pass

    @property
    @abstractmethod
    def base(self) -> "Node | None":
        pass

    def is_ancestor_of(self, node: "Node") -> bool:
        """True if `self` is `node` or one of its bases."""
        curr_node = node
        while curr_node is not None:
            if self is curr_node:
                return True
            curr_node = curr_node.base
        return False

    @property
    @abstractmethod
    def image(self) -> str:
        """The docker image name, without the registry or tag."""

    @abstractmethod
    def dockerfile(self) -> str | None:
        """The dockerfile that builds this image, or None if it is built elsewhere."""

    @abstractmethod
    def to_install(self) -> frozenset[str]:
        pass

    def contents(self) -> frozenset[str]:
        """The packages actually in `node`'s image: what it and all of its bases install."""
        return (
            self.base.contents() if self.base is not None else frozenset()
        ) | self.to_install()


@dataclass(frozen=True)
class BaseImage(Node):
    """A scale-test-$distro image. This is the root of the graph: it has no outgoing edge."""

    distro: str

    @property
    def base(self) -> "Node | None":
        return None

    @property
    def name(self) -> str:
        return f"scale-test-{self.distro}"

    @property
    def image(self) -> str:
        return self.name

    def dockerfile(self) -> str | None:
        # Built from ci/images.
        return None

    @property
    def installed(self) -> frozenset[str]:
        return frozenset()

    def to_install(self) -> frozenset[str]:
        return frozenset()


@dataclass
class ProjectImage(Node):
    """A project builder image. It always has exactly one base image."""

    project: str
    distro: str
    _installed: frozenset[str]
    _base: "Node"

    @property
    def name(self) -> str:
        return self.project

    @property
    def installed(self) -> frozenset[str]:
        return self._installed

    @property
    def base(self) -> "Node | None":
        return self._base

    @property
    def image(self) -> str:
        # Docker image names must be lowercase.
        return f"thirdparty-{self.name.lower()}-{self.distro}"

    def dockerfile(self) -> str | None:
        lines = [
            "# Generated by test/thirdparty/util/image_graph.py. Do not edit.",
            "ARG PRIVATE_DOCKER_REGISTRY",
            "ARG BASE_DOCKER_TAG",
            f"FROM ${{PRIVATE_DOCKER_REGISTRY}}spectral/{self._base.image}:$BASE_DOCKER_TAG",
        ]
        if commands := install_commands(self.to_install()):
            lines += ["", "USER root", *commands, "USER stressedtuna"]
        return "\n".join(lines) + "\n"

    def to_install(self) -> frozenset[str]:
        """The packages this image installs on top of its base."""
        return self.installed - self._base.installed


@dataclass
class LayerImage(ProjectImage):
    """An intermediate image split out of a project image. It installs one package."""

    layer: int

    @property
    def name(self) -> str:
        return f"{self.project}-layer{self.layer}"


# Parsing and initial construction stuff
def install_commands(packages: frozenset[str]) -> list[str]:
    """Dockerfile commands that install `<source>:<package>` strings, run as root."""
    by_source: dict[str, list[str]] = {}
    for entry in sorted(packages):
        source, package = entry.split(":", 1)
        by_source.setdefault(source, []).append(package)

    commands: list[str] = []
    # Distro packages go first, because pip and pipx may come from them.
    if apt := by_source.pop("apt", None):
        commands.append(
            f"RUN apt-get update && apt-get install -y {shlex.join(apt)}"
            " && rm -rf /var/lib/apt/lists/*"
        )
    if dnf := by_source.pop("dnf", None):
        commands.append(f"RUN dnf install -y {shlex.join(dnf)} && dnf clean all")
    if pip := by_source.pop("pip", None):
        # Older pip versions ignore this variable, so it is safe on every distro.
        commands.append(
            f"RUN PIP_BREAK_SYSTEM_PACKAGES=1 pip3 install {shlex.join(pip)}"
        )
    if pipx := by_source.pop("pipx", None):
        # Install outside any home directory, so every user can run them.
        commands.append(
            "RUN PIPX_HOME=/opt/pipx PIPX_BIN_DIR=/usr/local/bin"
            f" pipx install {shlex.join(pipx)}"
        )
    for package in by_source.pop("ext", []):
        commands.append(
            "RUN --mount=type=bind,source=install-ext.sh,target=/install-ext.sh"
            f" /install-ext.sh {shlex.quote(package)}"
        )
    if by_source:
        raise ValueError(f"Unknown package sources: {sorted(by_source)}")
    return commands


def read_dependencies(path: Path) -> dict[str, frozenset[str]]:
    """Read a `.dependencies` file. Returns `<source>:<package>` strings by distro."""
    by_distro: dict[str, set[str]] = {}
    for line in path.read_text().splitlines():
        if not line.strip():
            continue
        distro, source, package = line.split(":", 2)
        by_distro.setdefault(distro, set()).add(f"{source}:{package}")
    return {distro: frozenset(packages) for distro, packages in by_distro.items()}


def build_graph() -> tuple[dict[str, BaseImage], list[ProjectImage]]:
    """Make one node per project and distro, each based on scale-test-$distro."""
    deps = {
        path.parent.name: read_dependencies(path)
        for path in sorted(REPO_BASE.glob("*/.dependencies"))
    }
    roots = {
        distro: BaseImage(distro) for by_distro in deps.values() for distro in by_distro
    }
    projects: list[ProjectImage] = []
    for project, by_distro in deps.items():
        # An empty file means the project needs only scale-test, on every distro.
        if not by_distro:
            by_distro = {distro: frozenset() for distro in roots}
        for distro, packages in by_distro.items():
            projects.append(ProjectImage(project, distro, packages, roots[distro]))
    return roots, projects


# Optimisation passes
def split(projects: list[ProjectImage], rng: random.Random) -> list[ProjectImage]:
    """Split each project into a chain of images that each install one package.

    Packages that more projects on the same distro need are installed first. Ties are
    broken by a random order, which is the same for every project. Returns the projects
    and the new layer images.
    """
    users = Counter((p.distro, package) for p in projects for package in p.installed)
    # Sort first, so the order depends only on `rng`.
    tie_break = sorted(users)
    rng.shuffle(tie_break)
    rank = {key: i for i, key in enumerate(tie_break)}

    nodes: list[ProjectImage] = []
    for p in projects:
        packages = sorted(
            p.installed,
            key=lambda package: (-users[p.distro, package], rank[p.distro, package]),
        )
        base = p._base
        # The project image itself installs the last package.
        for i, package in enumerate(packages[:-1], 1):
            base = LayerImage(p.project, p.distro, base.installed | {package}, base, i)
            nodes.append(base)
        p._base = base
        nodes.append(p)
    return nodes


def optimise(roots: dict[str, BaseImage], projects: list[ProjectImage]) -> None:
    """Repoint each project at the image whose packages are the largest subset of its own.

    Repeats until nothing changes. A node may not be based on itself or its descendants,
    so the graph stays a tree.
    """
    changed = True
    while changed:
        changed = False
        for x in projects:
            candidates: list[Node] = [roots[x.distro]]
            candidates += [
                y
                for y in projects
                if y.distro == x.distro
                and y.installed <= x.installed
                and not x.is_ancestor_of(y)
            ]
            # On a tie, prefer the scale-test image, then the first project by name.
            best = min(
                candidates,
                key=lambda y: (-len(y.installed), isinstance(y, ProjectImage), y.name),
            )
            if best is not x.base:
                x._base = best
                changed = True


def remove_empty(nodes: list[ProjectImage]) -> list[ProjectImage]:
    """Remove layer images that install nothing. Their children use their base instead.

    Project images are always kept, because they are the images we need.
    """

    def is_empty(node: Node) -> bool:
        return isinstance(node, LayerImage) and not node.to_install()

    for n in nodes:
        while isinstance(n.base, LayerImage) and is_empty(n.base):
            assert n.base is not None
            assert n.base.base is not None
            n._base = n.base.base
    return [n for n in nodes if not is_empty(n)]


def remove_unused(nodes: list[ProjectImage]) -> list[ProjectImage]:
    """Remove layer images that no image uses as a base, until none are left."""
    while True:
        bases = {id(n.base) for n in nodes}
        kept = [n for n in nodes if not isinstance(n, LayerImage) or id(n) in bases]
        if len(kept) == len(nodes):
            return kept
        nodes = kept


def merge_single_children(nodes: list[ProjectImage]) -> list[ProjectImage]:
    """Merge each layer image that only one image uses into that image, until none are left.

    The child is rebased onto the layer's base, so it installs the layer's packages too.
    """
    while True:
        children = Counter(id(n.base) for n in nodes)
        for x in nodes:
            if isinstance(x, LayerImage) and children[id(x)] == 1:
                y = next(n for n in nodes if n.base is x)
                y._base = x._base
                nodes = [n for n in nodes if n is not x]
                break
        else:
            return nodes


# Correctness checks
def write_dockerfiles(node: Node, nodes: list[ProjectImage], out_dir: Path) -> None:
    """Write the dockerfile for `node` and every image based on it, recursively."""
    if (text := node.dockerfile()) is not None:
        (out_dir / f"{node.image}.dockerfile").write_text(text)
    for child in nodes:
        if child.base is node:
            write_dockerfiles(child, nodes, out_dir)


def check_exact(projects: list[ProjectImage]) -> None:
    """Raise if any project's image has packages other than the ones it needs."""
    for p in projects:
        if p.contents() != p.installed:
            raise RuntimeError(
                f"{p.name} on {p.distro} would contain {sorted(p.contents())},"
                f" but needs exactly {sorted(p.installed)}"
            )


# Driving code
def plan(
    rng: random.Random,
) -> tuple[dict[str, BaseImage], list[ProjectImage], list[ProjectImage]]:
    """Run every pass. Returns the roots, the project images and all the images."""
    roots, projects = build_graph()
    nodes = split(projects, rng)
    optimise(roots, nodes)
    nodes = merge_single_children(remove_unused(remove_empty(nodes)))
    check_exact(projects)
    return roots, projects, nodes


def print_tree(node: Node, projects: list[ProjectImage], depth: int = 0) -> None:
    line = "    " * depth + node.name
    if isinstance(node, ProjectImage):
        line += ": " + " ".join(sorted(node.to_install()))
    print(line.rstrip())
    for child in sorted(projects, key=lambda p: p.name):
        if child.base is node:
            print_tree(child, projects, depth + 1)


def main(seed: int | None = None) -> None:
    roots, _, nodes = plan(random.Random(seed))
    out_dir = Path.cwd() / "images"
    out_dir.mkdir(exist_ok=True)
    # Layer images change between runs, so remove old dockerfiles.
    for old in out_dir.glob("*.dockerfile"):
        old.unlink()
    for distro in sorted(roots):
        print_tree(roots[distro], nodes)
        write_dockerfiles(roots[distro], nodes, out_dir)


if __name__ == "__main__":
    main()
