[project]
name = "scale-validation-util"
version = "0.1.0"
description = "Utilities for working with scale-validation"
readme = "README.md"
authors = [
    { name = "Aria Shrimpton", email = "aria@spectralcompute.co.uk" }
]
requires-python = ">=3.13"
dependencies = []

[dependency-groups]
dev = [
    "pyright>=1.1.414",
    "pytest>=9.0.3",
    "ruff>=0.16.6",
]

[tool.pyright]
venvPath = "."
venv = ".venv"
